import Header from '@/components/layout/Header';
import type { Metadata } from 'next';
import { Outfit } from 'next/font/google';
import './globals.css';

const outfit = Outfit({
  variable: '--font-outfit',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Entertainment Web App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${outfit.variable} antialiased`}>
        <div className='relative lg:max-w-[1372px] lg:w-[96%] lg:mx-auto lg:grid lg:grid-cols-[auto_1fr] lg:gap-9'>
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
