import type { Metadata } from 'next';
import './globals.css';
import Header from '@/components/Header';
import SearchBox from '@/components/SearchBox';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang='en'>
      <body className='bg-blue-900 antialiased min-h-[3000px] lg:flex 3xl:mx-auto 3xl:max-w-3xl'>
        <Header />
        <main className='pt-6 pb-15 xs:pt-8 xs:pb-14 lg:flex-1'>
          <SearchBox />
          {children}
        </main>
      </body>
    </html>
  );
};

export default RootLayout;
