import type { Metadata } from 'next';
import './globals.css';
import Header from '@/components/Header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang='en'>
      <body className={`bg-blue-900 antialiased min-h-[3000px] lg:flex lg:gap-9`}>
        <Header />
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
